# Generated by Django 4.2.13 on 2024-07-15 10:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US', unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('enquiry', models.BooleanField(default=False)),
                ('enrollment', models.BooleanField(default=False)),
                ('attendance', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('placement', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
