# Generated by Django 4.2.13 on 2024-07-21 13:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0003_alter_newuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
