# Generated by Django 4.2.13 on 2024-07-22 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0004_alter_newuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
