# Generated by Django 4.2.13 on 2024-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0007_remove_newuser_name_newuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
