# Generated by Django 4.2.13 on 2024-08-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0012_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField()),
                ('enquiry_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_contact_no', models.CharField(max_length=10, unique=True)),
                ('fathers_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('inplant_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('inplant_no_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('internship_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('internship_no_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('grade_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('mode_of_enquiry', models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'Whatsapp'), ('Direct Walk-in', 'Direct walk-in'), ('Email Enquiry', 'Email Enquiry'), ('Direct Call', 'Direct call'), ('Reference', 'Reference'), ('Other', 'Other')], max_length=20)),
                ('reference_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('other_enquiry_details', models.TextField(blank=True, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.course')),
            ],
        ),
    ]
