# Generated by Django 4.2.13 on 2024-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0014_alter_enquiry_enquiry_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
