# Generated by Django 4.2.13 on 2024-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0015_alter_enquiry_degree_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_no',
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_no_of_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
