# Generated by Django 4.2.13 on 2024-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0016_alter_enquiry_degree_alter_enquiry_enquiry_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='inplant_no_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='grade_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_technology',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference_contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
