# Generated by Django 4.2.13 on 2024-08-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0019_enquiry_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mode_of_enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.enquiry_mode'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference_contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
