# Generated by Django 4.2.13 on 2024-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0020_alter_enquiry_mode_of_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_no_of_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_no_of_students',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
