# Generated by Django 4.2.13 on 2024-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0022_enquiry_lead_type_alter_enquiry_inplant_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='grade_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
