# Generated by Django 4.2.13 on 2024-08-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0023_alter_enquiry_grade_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
