# Generated by Django 4.2.13 on 2024-08-17 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0024_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
