# Generated by Django 4.2.13 on 2024-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0026_notes_enquiry_enquiry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_no_of_days',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='inplant_no_of_students',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='internship_no_of_days',
            field=models.CharField(blank=True, null=True),
        ),
    ]
