# Generated by Django 4.2.13 on 2024-08-17 13:50

import Nschool_CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0027_alter_enquiry_inplant_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='files',
            field=models.ImageField(default='Nschool_CRM_Project\\static\\media\\React.png', upload_to=Nschool_CRM.models.getFileName),
        ),
    ]
