# Generated by Django 4.2.13 on 2024-08-17 16:25

import Nschool_CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0029_alter_enquiry_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='files',
            field=models.ImageField(default='/media/React.png', upload_to=Nschool_CRM.models.getFileName),
        ),
    ]
