# Generated by Django 4.2.13 on 2024-08-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0031_alter_enquiry_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.notes'),
        ),
    ]
