# Generated by Django 4.2.13 on 2024-08-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0033_alter_enquiry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nschool_CRM.notes'),
        ),
    ]
