# Generated by Django 4.2.13 on 2024-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0034_alter_enquiry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='grade_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
