# Generated by Django 4.2.13 on 2024-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0036_alter_enquiry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='grade_percentage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
