# Generated by Django 4.2.13 on 2024-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0037_alter_enquiry_grade_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user_id',
            field=models.CharField(default=0),
        ),
    ]
