# Generated by Django 4.2.13 on 2024-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0038_notes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
