# Generated by Django 4.2.13 on 2024-08-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0039_alter_notes_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email_id', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=255)),
                ('fathers_contact_no', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('grade_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_experience', models.IntegerField(help_text='Enter work experience in years')),
                ('designation', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('course_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('total_fees_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enquiry_no', models.ForeignKey(db_column='enquiry_no', on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.enquiry', to_field='enquiry_no')),
            ],
        ),
    ]
