# Generated by Django 4.2.13 on 2024-08-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0040_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.course'),
        ),
    ]
