# Generated by Django 4.2.13 on 2024-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0042_remove_enrollment_work_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_type',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(null=True),
        ),
    ]
