# Generated by Django 4.2.13 on 2024-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0043_enrollment_payment_type_alter_enrollment_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='year_of_passed_out',
            field=models.PositiveIntegerField(),
        ),
    ]
