# Generated by Django 4.2.13 on 2024-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0044_alter_enrollment_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='to_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='work_experience',
            field=models.CharField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
