# Generated by Django 4.2.13 on 2024-08-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0045_remove_enrollment_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='inplant_no_of_days',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='inplant_no_of_students',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='inplant_technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='internship_no_of_days',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='internship_no_of_students',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='internship_technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
