# Generated by Django 4.2.13 on 2024-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0046_enrollment_inplant_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
