# Generated by Django 4.2.13 on 2024-09-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0047_newuser_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
                ('fees_type', models.CharField()),
                ('payment_mode', models.CharField()),
                ('installment', models.CharField()),
                ('cash', models.CharField()),
                ('date', models.DateField()),
                ('transaction_id', models.CharField()),
                ('bank_name', models.CharField()),
                ('app_name', models.CharField()),
                ('account_no', models.CharField()),
                ('ifsc_code', models.CharField()),
                ('branch_name', models.CharField()),
                ('account_holder_name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nschool_CRM.course')),
            ],
        ),
    ]
