# Generated by Django 4.2.13 on 2024-09-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0048_enrollment_created_by_enrollment_modified_by_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_name',
            field=models.CharField(),
        ),
    ]
