# Generated by Django 4.2.13 on 2024-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0052_rename_date_payment_bank_date_payment_bank_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
