# Generated by Django 4.2.13 on 2024-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0053_payment_date_alter_payment_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_EMI_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_EMI_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_EMI_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_EMI_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_EMI_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_EMI_6',
            field=models.DateField(blank=True, null=True),
        ),
    ]
