# Generated by Django 4.2.13 on 2024-09-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0058_installment_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='bank_account_holder_name',
            new_name='refference_no',
        ),
        migrations.RenameField(
            model_name='singlepayment',
            old_name='bank_account_holder_name',
            new_name='refference_no',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='bank_account_no',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='bank_branch_name',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='bank_ifsc_code',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='upi_bank_name',
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='bank_account_no',
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='bank_branch_name',
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='bank_ifsc_code',
        ),
        migrations.RemoveField(
            model_name='singlepayment',
            name='upi_bank_name',
        ),
    ]
