# Generated by Django 4.2.13 on 2024-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0060_enrollment_installment_amount_emi_6_emi_5_emi_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='internship_no_of_students',
            field=models.CharField(blank=True, null=True),
        ),
    ]
