# Generated by Django 4.2.13 on 2024-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0061_enquiry_internship_no_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
