# Generated by Django 4.2.13 on 2024-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0062_alter_enrollment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
    ]
