# Generated by Django 4.2.13 on 2024-09-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0064_alter_emi_1_status_alter_emi_2_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi_1',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='emi_2',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='emi_3',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='emi_4',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='emi_5',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='emi_6',
            name='payment_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', to='Nschool_CRM.paymentinfo'),
        ),
    ]
