# Generated by Django 4.2.13 on 2024-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0065_alter_emi_1_payment_info_alter_emi_2_payment_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='excess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
