# Generated by Django 4.2.13 on 2024-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0066_paymentinfo_excess_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
