# Generated by Django 4.2.13 on 2024-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0067_paymentinfo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='remaining_emi_count',
            field=models.IntegerField(default=0),
        ),
    ]
