# Generated by Django 4.2.13 on 2024-09-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0068_paymentinfo_remaining_emi_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='remaining_emi_count',
        ),
    ]
