# Generated by Django 4.2.13 on 2024-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0070_emi_1_refference_no_emi_1_upi_app_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
