# Generated by Django 4.2.13 on 2024-09-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0071_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
