# Generated by Django 4.2.13 on 2024-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0073_course_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='S_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
