# Generated by Django 4.2.13 on 2024-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0074_alter_course_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='nature_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='work_experience',
            field=models.CharField(blank=True, null=True),
        ),
    ]
