# Generated by Django 4.2.13 on 2024-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0075_alter_enrollment_nature_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='monthly_payment_type',
        ),
        migrations.AddField(
            model_name='emi_1',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='emi_2',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='emi_3',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='emi_4',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='emi_5',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
        migrations.AddField(
            model_name='emi_6',
            name='monthly_payment_type',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=20),
        ),
    ]
