# Generated by Django 4.2.13 on 2024-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0077_singlepayment_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepayment',
            name='registration_no',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
