# Generated by Django 4.2.13 on 2024-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0079_alter_singlepayment_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='fathers_email_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
