# Generated by Django 4.2.13 on 2024-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0081_remove_paymentinfo_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi_1',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_1',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_2',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_2',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_3',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_3',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_4',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_4',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_5',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_5',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_6',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi_6',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlepayment',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlepayment',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlepayment',
            name='date',
            field=models.DateField(),
        ),
    ]
