# Generated by Django 4.2.13 on 2024-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0083_alter_emi_1_amount_alter_emi_1_emi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
