# Generated by Django 4.2.13 on 2024-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0084_alter_singlepayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='fees_type',
            field=models.CharField(choices=[('Single Payment', 'Single Payment'), ('Installment', 'Installment')], max_length=20),
        ),
    ]
