# Generated by Django 4.2.13 on 2024-10-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0086_alter_emi_1_amount_alter_emi_2_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='class_status',
            field=models.CharField(choices=[('Yet To Start', 'Yet To Start'), ('On Going', 'On Going'), ('Discontinue', 'Discontinue'), ('Completed', 'Completed')], default='On Going', max_length=20),
        ),
    ]
