# Generated by Django 4.2.13 on 2024-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nschool_CRM', '0087_paymentinfo_class_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
    ]
